# docker composeファイルのバージョンを指定
version: "3.9"
services:
  app: # => サービス名は任意
    build: ./infra/php #=> ビルドコンテキスト、Dockerfileを置いてる場所を指す
    volumes: #=> ボリュームの保存先 ./backend => ホスト側/work に保存する
      - ./backend:/work
  # 追記
  web:
    image: nginx:1.20-alpine #=> コンテナを起動させるイメージを指定/image直の場合はDockerfile不要
    ports: #=> nginxへホスト側からアクセスするためのポート #ホスト側:コンテナ側
      - 8080:80
    volumes: #=> nginxへホスト側にあるソースをマウントしてる #ホスト側:コンテナ側
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    # 追記
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store: